source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'FirebaseGoogleAuthUI' do
  use_frameworks!

  pod 'GoogleSignIn', '~> 7.1.0'
  pod 'FirebaseAuthUI', :path => '../'

  target 'FirebaseGoogleAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
